/**
 * Tests that spawned agents inherit the parent channel on join,
 * even though the harness server's process.env doesn't have
 * PI_MESSENGER_CHANNEL set.
 *
 * The bug: resolveAgentState sets currentChannel from x-messenger-channel
 * header, but register() → ensureStateChannels() creates a new session
 * channel because it reads process.env.PI_MESSENGER_CHANNEL from the
 * *harness server* (which doesn't have it), not from the CLI caller.
 *
 * The fix: executeJoin saves the pre-existing channel before register(),
 * and restores it afterwards if register overwrote it.
 */

import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';
import type { Dirs, MessengerState } from '../../lib.js';
import { executeAction } from '../../router.js';
import { createMockContext } from '../helpers/mock-context.js';
import * as store from '../../store.js';

const roots = new Set<string>();

function createDirs(cwd: string): Dirs {
  const base = path.join(cwd, '.pi', 'messenger');
  const registry = path.join(base, 'registry');
  fs.mkdirSync(registry, { recursive: true });
  return { base, registry };
}

function createState(
  registered: boolean,
  currentChannel: string,
  overrides: Partial<MessengerState> = {}
): MessengerState {
  return {
    agentName: overrides.agentName ?? 'JoinAgent',
    registered,
    watcher: null,
    watcherRetries: 0,
    watcherRetryTimer: null,
    watcherDebounceTimer: null,
    reservations: [],
    chatHistory: new Map(),
    unreadCounts: new Map(),
    channelPostHistory: [],
    seenSenders: new Map(),
    model: 'test-model',
    gitBranch: undefined,
    spec: undefined,
    scopeToFolder: false,
    isHuman: false,
    session: { toolCalls: 0, tokens: 0, filesModified: [] },
    activity: { lastActivityAt: new Date().toISOString() },
    statusMessage: undefined,
    customStatus: false,
    registryFlushTimer: null,
    sessionStartedAt: new Date().toISOString(),
    contextSessionId: overrides.contextSessionId ?? 'test-session',
    currentChannel,
    sessionChannel: currentChannel || '',
    joinedChannels: currentChannel ? [currentChannel, 'memory'] : ['memory'],
    ...overrides,
  } as MessengerState;
}

afterEach(() => {
  for (const root of roots) {
    try {
      fs.rmSync(root, { recursive: true, force: true });
    } catch {
      // ignore
    }
  }
});

describe('join channel inheritance for spawned agents', () => {
  it('preserves the pre-set channel when joining unregistered (simulates resolveAgentState from x-messenger-channel header)', async () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-messenger-join-inherit-'));
    roots.add(cwd);
    const dirs = createDirs(cwd);

    // State simulates what resolveAgentState does when x-messenger-channel=mint-zenith:
    // - registered: false (spawned agent hasn't joined yet)
    // - currentChannel: 'mint-zenith' (set by resolveAgentState from header)
    // - sessionChannel: 'mint-zenith' (also set by resolveAgentState)
    const state = createState(false, 'mint-zenith', {
      contextSessionId: 'test-session-1',
    });

    const ctx = createMockContext(cwd);

    const result = await executeAction(
      'join',
      {},
      state,
      dirs,
      ctx,
      () => {},
      () => {},
      undefined,
      { feedRetention: 50 }
    );

    // After the join, currentChannel should still be 'mint-zenith'
    // (not a new session channel generated by ensureStateChannels)
    expect(state.currentChannel).toBe('mint-zenith');
    expect(state.registered).toBe(true);
    expect(result.details.channel).toBe('mint-zenith');
  });

  it('creates a new session channel when no pre-set channel (normal join without spawn)', async () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-messenger-join-inherit-'));
    roots.add(cwd);
    const dirs = createDirs(cwd);

    // State simulates a fresh pi process joining for the first time:
    // - registered: false
    // - currentChannel: '' (no pre-set channel)
    // - sessionChannel: '' (no pre-set channel)
    const state = createState(false, '', {
      contextSessionId: 'test-session-2',
    });

    const ctx = createMockContext(cwd);

    const result = await executeAction(
      'join',
      {},
      state,
      dirs,
      ctx,
      () => {},
      () => {},
      undefined,
      { feedRetention: 50 }
    );

    // A new session channel should be created automatically
    expect(state.currentChannel).toBeTruthy();
    expect(state.currentChannel).not.toBe('');
    expect(state.registered).toBe(true);
    // Should NOT be the default test-channel
    expect(state.currentChannel).not.toBe('test-channel');
    // Should NOT be the pre-set mint-zenith either
    expect(state.currentChannel).not.toBe('mint-zenith');
  });

  it('respects explicit --channel flag over pre-set channel', async () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-messenger-join-inherit-'));
    roots.add(cwd);
    const dirs = createDirs(cwd);

    // State has pre-set channel from resolveAgentState, but user also
    // passed an explicit --channel flag to override it
    const state = createState(false, 'mint-zenith', {
      contextSessionId: 'test-session-3',
    });

    const ctx = createMockContext(cwd);

    const result = await executeAction(
      'join',
      { channel: 'dev', create: true },
      state,
      dirs,
      ctx,
      () => {},
      () => {},
      undefined,
      { feedRetention: 50 }
    );

    // Explicit --channel flag should take priority over pre-set channel
    expect(state.currentChannel).toBe('dev');
    expect(state.registered).toBe(true);
    expect(result.details.channel).toBe('dev');
  });

  it('does not affect already-registered agent that switches channels', async () => {
    const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'pi-messenger-join-inherit-'));
    roots.add(cwd);
    const dirs = createDirs(cwd);

    // Start fresh, let register create a session channel
    const state = createState(false, '', {
      contextSessionId: 'test-session-4',
    });

    const ctx = createMockContext(cwd);

    // First join: register and get a session channel
    await executeAction(
      'join',
      {},
      state,
      dirs,
      ctx,
      () => {},
      () => {},
      undefined,
      { feedRetention: 50 }
    );

    const originalChannel = state.currentChannel;
    expect(originalChannel).toBeTruthy();

    // Second join call on an already-registered agent should
    // return immediately without changing anything
    const result2 = await executeAction(
      'join',
      {},
      state,
      dirs,
      ctx,
      () => {},
      () => {},
      undefined,
      { feedRetention: 50 }
    );

    // Already-registered agents should not change channel
    expect(state.currentChannel).toBe(originalChannel);
    expect(result2.details.alreadyJoined).toBe(true);
  });
});
